
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='Mop',
    version='0.1.2-alpha.0',
    description='MPEG ID3 tagger using Python, eyeD3, and GTK+',
    python_requires='==3.*,>=3.8.0',
    project_urls={"documentation": "", "homepage": "https://github.com/nicfit/Mop", "repository": "https://github.com/nicfit/Mop"},
    author='Travis Shirk',
    author_email='travis@pobox.com',
    license='GPL-3.0-or-later',
    keywords='mp3 id3 gtk eyed3 ',
    classifiers=['Environment :: X11 Applications :: GTK', 'Intended Audience :: End Users/Desktop', 'Topic :: Multimedia :: Sound/Audio :: Editors'],
    entry_points={"console_scripts": ["mop = mop.__main__:main"]},
    packages=['mop', 'mop.editor'],
    package_dir={"": "."},
    package_data={"mop": ["*.ui"]},
    install_requires=['eyed3[art-plugin]>=0.9.5', 'nicfit.py>=0.8.6', 'pygobject>=3.38.0'],
    extras_require={"dev": ["check-manifest==0.*,>=0.45.0", "dephell==0.*,>=0.8.3", "pygobject-stubs>=0.0.2", "pytest==6.*,>=6.1.2", "regarding==0.*,>=0.1.2", "tox==3.*,>=3.20.1", "twine==3.*,>=3.2.0", "wheel==0.*,>=0.36.1"]},
)
